version: "3"

services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    build:
      context: ../..
      dockerfile: ./docker/alpine/Dockerfile
    ports:
      - "${SERVER_PORT:-8388}:${SERVER_PORT:-8388}/tcp"
      - "${SERVER_PORT:-8388}:${SERVER_PORT:-8388}/udp"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8388}
      - METHOD=${METHOD:-aes-256-gcm}
      - PASSWORD=${PASSWORD:-9MLSpPmNt}
    restart: always
